language: racket
sudo: required

env:
 - RACKET_VERSION=6.6
 - RACKET_VERSION=HEAD

before_install:
- git clone https://github.com/greghendershott/travis-racket.git
- cat travis-racket/install-racket.sh | bash

install:

before_script:

script:
 - make travis

after_script:
